//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;
using Oddin.OddsFeedSdk.API.Entities.Abstractions;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Oddin.OddsFeedSdk.API.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("competitor_profile", IsNullable = false)]
    public partial class competitorProfileEndpoint : ITeam
    {

        private teamExtended competitorField;

        private System.DateTime generated_atField;

        private bool generated_atFieldSpecified;

        /// <remarks/>
        public teamExtended competitor
        {
            get
            {
                return this.competitorField;
            }
            set
            {
                this.competitorField = value;
            }
        }

        /// <remarks/>
        [XmlArray("players")]
        [XmlArrayItem("player")]
        public List<player_profilePlayer> players { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime generated_at
        {
            get
            {
                return this.generated_atField;
            }
            set
            {
                this.generated_atField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generated_atSpecified
        {
            get
            {
                return this.generated_atFieldSpecified;
            }
            set
            {
                this.generated_atFieldSpecified = value;
            }
        }

        public string refid => competitor?.refid;

        public bool virtualSpecified => competitor?.virtualSpecified ?? false;

        public bool @virtual => competitor?.@virtual ?? false;

        public string country_code => competitor?.country_code;

        public string underage => competitor?.underage;

        public string name => competitor?.name;

        public string abbreviation => competitor?.abbreviation;

        public string country => competitor?.country;
    }
}
