//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Oddin.OddsFeedSdk.API.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("fixtures_fixture", IsNullable = false)]
    public partial class FixturesEndpointModel
    {

        private fixture fixtureField;

        private System.DateTime generated_atField;

        private bool generated_atFieldSpecified;

        /// <remarks/>
        public fixture fixture
        {
            get
            {
                return this.fixtureField;
            }
            set
            {
                this.fixtureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime generated_at
        {
            get
            {
                return this.generated_atField;
            }
            set
            {
                this.generated_atField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generated_atSpecified
        {
            get
            {
                return this.generated_atFieldSpecified;
            }
            set
            {
                this.generated_atFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fixture : sportEvent
    {

        private delayedInfo delayed_infoField;

        private tvChannel[] tv_channelsField;

        private info[] extra_infoField;

        private bool start_time_confirmedField;

        private bool start_time_confirmedFieldSpecified;

        private System.DateTime start_timeField;

        private bool start_timeFieldSpecified;

        private System.DateTime next_live_timeField;

        private bool next_live_timeFieldSpecified;

        /// <remarks/>
        public delayedInfo delayed_info
        {
            get
            {
                return this.delayed_infoField;
            }
            set
            {
                this.delayed_infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tv_channel", IsNullable = false)]
        public tvChannel[] tv_channels
        {
            get
            {
                return this.tv_channelsField;
            }
            set
            {
                this.tv_channelsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public info[] extra_info
        {
            get
            {
                return this.extra_infoField;
            }
            set
            {
                this.extra_infoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool start_time_confirmed
        {
            get
            {
                return this.start_time_confirmedField;
            }
            set
            {
                this.start_time_confirmedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool start_time_confirmedSpecified
        {
            get
            {
                return this.start_time_confirmedFieldSpecified;
            }
            set
            {
                this.start_time_confirmedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime start_time
        {
            get
            {
                return this.start_timeField;
            }
            set
            {
                this.start_timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool start_timeSpecified
        {
            get
            {
                return this.start_timeFieldSpecified;
            }
            set
            {
                this.start_timeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime next_live_time
        {
            get
            {
                return this.next_live_timeField;
            }
            set
            {
                this.next_live_timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool next_live_timeSpecified
        {
            get
            {
                return this.next_live_timeFieldSpecified;
            }
            set
            {
                this.next_live_timeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delayedInfo
    {

        private int idField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class info
    {

        private string keyField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tvChannel
    {

        private string nameField;

        private System.DateTime start_timeField;

        private bool start_timeFieldSpecified;

        private string stream_urlField;

        private string languageField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime start_time
        {
            get
            {
                return this.start_timeField;
            }
            set
            {
                this.start_timeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool start_timeSpecified
        {
            get
            {
                return this.start_timeFieldSpecified;
            }
            set
            {
                this.start_timeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stream_url
        {
            get
            {
                return this.stream_urlField;
            }
            set
            {
                this.stream_urlField = value;
            }
        }
    }
}
