//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace Oddin.OddsFeedSdk.API.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
    public partial class MatchStatusModel
    { 
        private match_status_description[] match_statusField;

        private response_code response_codeField;

        private bool response_codeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("match_status")]
        public match_status_description[] match_status
        {
            get
            {
                return this.match_statusField;
            }
            set
            {
                this.match_statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public response_code response_code
        {
            get
            {
                return this.response_codeField;
            }
            set
            {
                this.response_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool response_codeSpecified
        {
            get
            {
                return this.response_codeFieldSpecified;
            }
            set
            {
                this.response_codeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class match_status_description
    {

        private long idField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum response_code
    {

        /// <remarks/>
        OK,

        /// <remarks/>
        CREATED,

        /// <remarks/>
        ACCEPTED,

        /// <remarks/>
        FORBIDDEN,

        /// <remarks/>
        NOT_FOUND,

        /// <remarks/>
        CONFLICT,

        /// <remarks/>
        SERVICE_UNAVAILABLE,

        /// <remarks/>
        NOT_IMPLEMENTED,

        /// <remarks/>
        MOVED_PERMANENTLY,

        /// <remarks/>
        BAD_REQUEST,
    }
}