//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
using Oddin.OddsFeedSdk.AMQP.Messages;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
public partial class fixture_change : FeedMessageModel
{
    public override long GeneratedAt => timestampField;

    private int productField;

    private string event_idField;

    private long timestampField;

    private long request_idField;

    private bool request_idFieldSpecified;

    private int change_typeField;

    private bool change_typeFieldSpecified;

    private long start_timeField;

    private long next_live_timeField;

    private bool next_live_timeFieldSpecified;

    private string event_refidField;

    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "event_ref_id")]
    public string event_refid
    {
        get
        {
            return this.event_refidField;
        }
        set
        {
            this.event_refidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int product
    {
        get
        {
            return this.productField;
        }
        set
        {
            this.productField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string event_id
    {
        get
        {
            return this.event_idField;
        }
        set
        {
            this.event_idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long request_id
    {
        get
        {
            return this.request_idField;
        }
        set
        {
            this.request_idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool request_idSpecified
    {
        get
        {
            return this.request_idFieldSpecified;
        }
        set
        {
            this.request_idFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int change_type
    {
        get
        {
            return this.change_typeField;
        }
        set
        {
            this.change_typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool change_typeSpecified
    {
        get
        {
            return this.change_typeFieldSpecified;
        }
        set
        {
            this.change_typeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long start_time
    {
        get
        {
            return this.start_timeField;
        }
        set
        {
            this.start_timeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long next_live_time
    {
        get
        {
            return this.next_live_timeField;
        }
        set
        {
            this.next_live_timeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool next_live_timeSpecified
    {
        get
        {
            return this.next_live_timeFieldSpecified;
        }
        set
        {
            this.next_live_timeFieldSpecified = value;
        }
    }
}
